- name: playbook variable
  hosts: local
  connection: local
  vars:
   Couser: Devops with Aws
   Duration: 180hr
   Trainer: sivakumar
  tasks:
  - name: print the varibles
    vars:
     Couser: ansible
    ansible.builtin.debug:
     msg: "i am leaning {{ Couser }}, Duration of the course is {{ Duration }} and trainer is {{ Trainer }}"

  - name: print the varibles
    ansible.builtin.debug:
     msg: "i am leaning {{ Couser }}, Duration of the course is {{ Duration }} and trainer is {{ Trainer }}"

  
  
    
  